services:
  - type: web
    name: medbot-backend
    env: python
    region: ohio
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_DEBUG
        value: "false"
      - key: FLASK_PORT
        value: "8080"
      - key: PYTHON_VERSION
        value: "3.12.8"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
